@startuml domain-model

entity 社員 {
    社員名
    入社年月日:年月日
    勤怠情報[]
    今年度有給休暇残日数
    前年度有給休暇残日数
    有給休暇総残日数(): 整数
}

entity 有給休暇申請 {
    社員
    有給休暇使用日: 年月日[]
}

class 勤怠情報 <<値オブジェクト>> {
    年月日
    出欠勤
    有給休暇使用: 真偽値
    勤務開始時刻
    勤務終了時刻
}

class 有給休暇申請メール <<値オブジェクト>> {
    宛先
    緊急連絡先
    有給休暇使用日: 年月日[]
    有給休暇残日数
}

class 勤怠登録サービス {
    勤怠登録(社員, 勤怠情報): 真偽値
}

class 有給休暇申請サービス {
    有給休暇の使用(有給休暇申請): 勤怠情報[]
}

class 有給休暇処理サービス {
    有給休暇の付与(社員): 真偽値
    有給休暇の使用(社員): 勤怠情報
}

class メール送信サービス {
    有給休暇申請メール送信(社員, 勤怠情報[])
}

社員 <.. 勤怠登録サービス
有給休暇申請 ..> 有給休暇申請サービス
勤怠登録サービス <.. 勤怠情報
有給休暇申請サービス ..> 有給休暇処理サービス : 「有給休暇の使用(社員)」を実行
勤怠登録サービス <.. 有給休暇処理サービス
メール送信サービス <.. 有給休暇申請サービス
社員 .. 有給休暇申請
社員 "1" *- "*" 勤怠情報
有給休暇申請メール --> メール送信サービス

@enduml
